import Foundation

/// A single captured notification, shared between the main app and the
/// Notification Service Extension via the App Group container.
///
/// Trimmed from Pager's version of this type down to the fields Canopy
/// Mobile's push payload actually carries (see the worker's `NotifyBody` in
/// `worker/src/types.ts`). Pager's `project`, `toolName` and `source` are
/// dropped rather than copied over — nothing in this payload writes them,
/// and a field nothing writes is a field that will be wrong.
/// One question of an `AskUserQuestion`, as the push carries it.
///
/// The answer format is not ours: the extension keys its answer map by the
/// question's own TEXT and joins chosen labels with `", "` — read out of its
/// `webview/index.js`, measured against 2.1.260 and unchanged in 2.1.90.
/// `question` is therefore an identifier, not just a caption; shortening it
/// for display would break the answer.
struct AskChoice: Codable, Hashable, Sendable {
    let question: String
    let header: String?
    let options: [String]
    let multiSelect: Bool

    /// Decoded from the push, where a missing `multiSelect` means single.
    init(question: String, header: String? = nil, options: [String], multiSelect: Bool = false) {
        self.question = question
        self.header = header
        self.options = options
        self.multiSelect = multiSelect
    }

    /// Hand-written so a form built from `userInfo` — plain `Any` out of an
    /// APNs payload, never `Data` — can be decoded with the same rules.
    init?(userInfo: [String: Any]) {
        guard let question = userInfo["question"] as? String, !question.isEmpty,
              let options = userInfo["options"] as? [String], !options.isEmpty
        else { return nil }
        self.question = question
        self.header = userInfo["header"] as? String
        self.options = options
        self.multiSelect = userInfo["multiSelect"] as? Bool ?? false
    }

    /// The whole form from a push, or nil if any part of it is unusable.
    ///
    /// **All or nothing, and duplicates are unusable.** Dropping a
    /// malformed entry would draw a form missing a question; the phone only
    /// checks the form it has, so it would call itself complete and send an
    /// answer the Mac refuses for omitting a question it did ask, leaving the
    /// user with "not delivered" and no better move. And two questions
    /// sharing one text cannot be represented at all — the answer map is
    /// keyed by that text (the extension's own form state is too), so one
    /// selection would answer both. Both cases fall back to the no-buttons
    /// rendering, which still works: the ask is answered at the Mac.
    static func form(userInfo: Any?) -> [AskChoice]? {
        guard let entries = userInfo as? [[String: Any]], !entries.isEmpty else { return nil }
        let parsed = entries.compactMap(AskChoice.init(userInfo:))
        guard parsed.count == entries.count else { return nil }
        guard Set(parsed.map(\.question)).count == parsed.count else { return nil }
        return parsed
    }

    /// The answer map for a filled-in form, in the extension's own format:
    /// keyed by each question's TEXT, valued by the chosen labels joined with
    /// `", "`.
    ///
    /// Lives here rather than in the view so it can be tested without one —
    /// this is the only piece on the phone that has to match a format nobody
    /// on this side controls, and getting it wrong produces a refusal from
    /// the Mac rather than anything visible here.
    ///
    /// Labels are emitted in the order the OPTIONS were offered, not in set
    /// order, so a multi-select answer reads the way the question was asked
    /// and is stable across taps. A question with nothing picked is omitted,
    /// which is what makes an incomplete map detectable as incomplete.
    static func answers(for form: [AskChoice], picked: [String: Set<String>]) -> [String: String] {
        var out: [String: String] = [:]
        for choice in form {
            let chosen = choice.options.filter { picked[choice.question]?.contains($0) == true }
            if !chosen.isEmpty { out[choice.question] = chosen.joined(separator: ", ") }
        }
        return out
    }

    /// Whether every question has a selection. The Mac refuses a partial
    /// answer, so sending one could only produce a refusal the user cannot
    /// act on.
    static func isComplete(form: [AskChoice], picked: [String: Set<String>]) -> Bool {
        form.allSatisfy { !(picked[$0.question] ?? []).isEmpty }
    }
}

struct NotificationHistoryItem: Codable, Identifiable, Hashable, Sendable {
    /// Stable identifier. Equals `requestId` for an `asking` push,
    /// otherwise a UUID generated by the extension.
    let id: String
    let receivedAt: Date
    let title: String
    /// Full body. The NSE fills it from `userInfo["bodyFull"]`, falling
    /// back to the APNs banner body (`aps.alert.body`) when that key is
    /// absent (e.g. a bare test push with no custom payload).
    let body: String
    /// LLM-shortened summary of `body`, produced by the worker for long
    /// `/notify` pushes. `nil` when the banner already equals the full
    /// body, so the list view's fallback to `body` renders the same text
    /// either way.
    let bodyShort: String?
    let machine: String
    let sessionId: String
    /// "completed" or "asking" — mirrors `NotifyBody.kind` in the worker.
    let kind: String
    /// Present only when `kind == "asking"`; the id the phone answers with.
    let requestId: String?
    var decision: String?
    var decidedAt: Date?
    /// Whether the relay accepted the decision. `nil` on an item with no
    /// decision, and on one written by a build that predates this field.
    /// **`false` is the state this exists for**: the user tapped Allow and
    /// the Mac never heard it, which is the exact "you believe you answered
    /// and the session is still blocked" failure the design doc argues this
    /// whole feature exists to remove. It must be visible, not inferred.
    var decisionDelivered: Bool?
    /// Whether the CLI proposed a rule for this ask. Only then does the UI
    /// offer "Always" — a button that quietly degraded to a plain Allow would
    /// tell the user they had made a standing decision they had not.
    var allowAlways: Bool?
    /// The CLI's own session id. `sessionId` is minted per Canopy process, so
    /// a restart orphans every stored notification from its session — the
    /// conversation came up empty and read as "the push never arrived"
    /// (measured 2026-09-05). Grouping prefers this when both sides have one.
    var resumeId: String?
    /// False for an ask Allow/Deny cannot resolve — an `AskUserQuestion`,
    /// whose answer is a chosen option. Allow/Deny are hidden then:
    /// answering one would echo the QUESTION back as the tool's input and
    /// resolve the request without ever supplying an answer.
    var answerable: Bool?
    /// An `AskUserQuestion`'s form. Present exactly when `answerable` is
    /// false — **and the pair is the whole fix**: `answerable == false` used
    /// to mean "show it with no buttons at all", which rendered the tool's
    /// input as raw JSON above a plain text field. The question was legible
    /// and unanswerable, on a push whose entire purpose is that the session
    /// is blocked. Absent on an item written by a build that predates this,
    /// and on an ask whose form did not fit the 4 KB push budget — in both
    /// cases the UI falls back to that older no-buttons rendering.
    var choices: [AskChoice]?

    init(
        id: String,
        receivedAt: Date,
        title: String,
        body: String,
        bodyShort: String? = nil,
        machine: String,
        sessionId: String,
        kind: String,
        requestId: String? = nil,
        decision: String? = nil,
        decidedAt: Date? = nil,
        decisionDelivered: Bool? = nil,
        allowAlways: Bool? = nil,
        resumeId: String? = nil,
        answerable: Bool? = nil,
        choices: [AskChoice]? = nil
    ) {
        self.id = id
        self.receivedAt = receivedAt
        self.title = title
        self.body = body
        self.bodyShort = bodyShort
        self.machine = machine
        self.sessionId = sessionId
        self.kind = kind
        self.requestId = requestId
        self.decision = decision
        self.decidedAt = decidedAt
        self.decisionDelivered = decisionDelivered
        self.allowAlways = allowAlways
        self.resumeId = resumeId
        self.answerable = answerable
        self.choices = choices
    }

    /// Jq and some pipelines pass through the four ASCII letters `null` as
    /// the string when a JSON `null` is stringified. Treat that as no body
    /// for display.
    static func displayableBody(_ body: String) -> String {
        if body == "null" { return "" }
        return body
    }

    /// The `AskUserQuestion` form to draw, or nil if there is nothing
    /// answerable here.
    ///
    /// **`requestId` is part of the test, and that is the whole reason this
    /// lives on the model.** The form commits optimistically — it disables
    /// itself and shows "Sending…" the moment Send is pressed — and the send
    /// path needs a `requestId` to address anything at all. Drawing a form
    /// without one produced a card that latched into "Sending…" with no
    /// request made, no history written, and no way back. Today the relay
    /// refuses an `asking` push with no `requestId` and Canopy only attaches
    /// `choices` alongside one, so this is unreachable through the live path
    /// — which is exactly why it belongs here as one local invariant rather
    /// than as a property of two other codebases agreeing.
    var answerableForm: [AskChoice]? {
        guard kind == "asking", decision == nil, answerable == false,
              requestId != nil, let choices, !choices.isEmpty
        else { return nil }
        return choices
    }

    /// Whether to render `body` in the conversation.
    ///
    /// **False once a form came through.** For an `AskUserQuestion` the body
    /// is the tool's input rendered as JSON — which, before `choices`
    /// existed, was the only thing there was to show. Now the questions and
    /// their options are drawn as controls directly underneath it, so the
    /// body is the same content twice, the longer and less useful time
    /// first: on device it pushed the buttons most of a screen down
    /// (measured 2026-09-05).
    ///
    /// Deliberately keyed on `choices`, not on whether the form is still
    /// answerable — an ANSWERED ask keeps its questions on screen for the
    /// recorded answer to refer to, and reverting to raw JSON at the moment
    /// it is answered would be the same duplication with worse timing.
    ///
    /// The History list is unaffected: it shows `listDisplayBody`, which is
    /// one line and is what makes an ask findable there.
    var showsBody: Bool {
        choices?.isEmpty != false
    }

    /// Single source of truth for "what the History list row should show":
    /// the worker-generated short summary if it exists, else the full body.
    /// Already `null`-cleaned so the row can render it directly.
    var listDisplayBody: String {
        Self.displayableBody(bodyShort ?? body)
    }
}
