import Foundation

/// A single captured notification, shared between the main app and the
/// Notification Service Extension via the App Group container.
///
/// Trimmed from Pager's version of this type down to the fields Canopy
/// Mobile's push payload actually carries (see the worker's `NotifyBody` in
/// `worker/src/types.ts`). Pager's `project`, `toolName` and `source` are
/// dropped rather than copied over — nothing in this payload writes them,
/// and a field nothing writes is a field that will be wrong.
struct NotificationHistoryItem: Codable, Identifiable, Hashable, Sendable {
    /// Stable identifier. Equals `requestId` for an `asking` push,
    /// otherwise a UUID generated by the extension.
    let id: String
    let receivedAt: Date
    let title: String
    /// Full body. The NSE fills it from `userInfo["bodyFull"]`, falling
    /// back to the APNs banner body (`aps.alert.body`) when that key is
    /// absent (e.g. a bare test push with no custom payload).
    let body: String
    /// LLM-shortened summary of `body`, produced by the worker for long
    /// `/notify` pushes. `nil` when the banner already equals the full
    /// body, so the list view's fallback to `body` renders the same text
    /// either way.
    let bodyShort: String?
    let machine: String
    let sessionId: String
    /// "completed" or "asking" — mirrors `NotifyBody.kind` in the worker.
    let kind: String
    /// Present only when `kind == "asking"`; the id the phone answers with.
    let requestId: String?
    var decision: String?
    var decidedAt: Date?

    init(
        id: String,
        receivedAt: Date,
        title: String,
        body: String,
        bodyShort: String? = nil,
        machine: String,
        sessionId: String,
        kind: String,
        requestId: String? = nil,
        decision: String? = nil,
        decidedAt: Date? = nil
    ) {
        self.id = id
        self.receivedAt = receivedAt
        self.title = title
        self.body = body
        self.bodyShort = bodyShort
        self.machine = machine
        self.sessionId = sessionId
        self.kind = kind
        self.requestId = requestId
        self.decision = decision
        self.decidedAt = decidedAt
    }

    /// Jq and some pipelines pass through the four ASCII letters `null` as
    /// the string when a JSON `null` is stringified. Treat that as no body
    /// for display.
    static func displayableBody(_ body: String) -> String {
        if body == "null" { return "" }
        return body
    }

    /// Single source of truth for "what the History list row should show":
    /// the worker-generated short summary if it exists, else the full body.
    /// Already `null`-cleaned so the row can render it directly.
    var listDisplayBody: String {
        Self.displayableBody(bodyShort ?? body)
    }
}
